namespace WMS.Service.CustomerLayer.Business.Filter.Formap
{
    public class SearchFilter
    {
        public int? Id { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public List<int> CustomerIds { get; set; }
        public List<int> CustomerProductIds { get; set; }
        public string TrailerNo { get; set; }
        public int? ReqFolio { get; set; }
        public int? OutFolio { get; set; }
        public string FolioType { get; set; }
        public string filterText { get; set; }
        public int WarehouseAddressId { get; set; }
        public int AddressId { get; set; }
        public int ResultCount { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public int CityId { get; set; }
        public int PostalCodeId { get; set; }
        public int CustomerId { get; set; }
        public List<int> CpIds { get; set; }
        public List<int> BinIds { get; set; }
        public int ProductCategoryId { get; set; }
        public int ProductUOMId { get; set; }
        public int ProductType { get; set; }
        public int ShippingWay { get; set; }
        public int? SearchStatus { get; set; }
        public List<int> TrailerIds { get; set; }
        public List<int> WHIds { get; set; }
        public List<int> EventTypeIds { get; set; }
        public int ViewType { get; set; }
        public string Printer { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? FinalTime { get; set; }
        public int? TransportationLineId { get; set; }
        public int? Folio { get; set; }
        public int? CustomerProductId { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string ExistenceOrInExistence { get; set; }
        public int? FolioId { get; set; }
        public string Container { get; set; }
        public int ReceiptType { get; set; }
        public int DriverId { get; set; }
        public string Type { get; set; }
        public string Location { get; set; }
        public string External { get; set; }
        public string Active { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public List<int> RoleIds { get; set; }
        public List<int> FolioIds { get; set; }
        public List<int> DetailIds { get; set; }
        public int ReceivingFolio { get; set; }
        public int TrailerFolio { get; set; }
        public List<int> StatusIds { get; set; }
        public string RefDetail2 { get; set; }
        public int? LabelPrinterStatus { get; set; }
        public string Lot { get; set; }
        public int SupplierId { get; set; }
        public List<int> SelectedSIDs { get; set; }
        public int IsSelectAll { get; set; }
        public List<int> SelectedCustomerProductIds { get; set; }
        public List<int> SelectedCustomerIds { get; set; }
        public int QualityStatusId { get; set; }
        public DateTime? fromDate { get; set; }
        public DateTime? toDate { get; set; }
        public int EndCustomer { get; set; }
        public int CqCustomerId { get; set; }
        public string Seal { get; set; }
        public string Release { get; set; }
        public string Bin { get; set; }
        public string Po { get; set; }
        public int PageType { get; set; }

        public int ShippingTrailerId { get; set; }
        public List<int> ReqIds { get; set; }
        public DateTime CurrDateForIMMEXCheck { get; set; }
        public int DriverPodId { get; set; }
        public int CustomerPodId { get; set; }
        public int CQCustomerId { get; set; }
        public int ToPicking { get; set; }
        public int FromPicking { get; set; }
        public List<int> ReqTypes { get; set; }
        public List<int> CQCustomerIds { get; set; }
        public int LocationId { get; set; }
        public int ExpiryMonths { get; set; }
        public decimal Quantity { get; set; }
        public int StatusId { get; set; }
        public int BinId { get; set; }
        public int ProductId { get; set; }
        public string EtiqMaster { get; set; }
        public int? CategoryId { get; set; }
        public string StageType { get; set; }
        public string ExcelStageType { get; set; }
        public double Days { get; set; }
        public int AddedBy { get; set; }
        public DateTime? AddedDate { get; set; }
        public int ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool AutomaticCalculate { get; set; }
        public double MinimumQty { get; set; }
        public double? MaximumQty { get; set; }
        public double MinSafetyStockPercentage { get; set; }
        public double MaxSafetyStockPercentage { get; set; }
        public string SendTo { get; set; }
        public string CQCustomer { get; set; }
        public string Customer { get; set; }
        public string Supplier { get; set; }
        public string Sku { get; set; }
        public string Category { get; set; }
        public string OnHandLevels { get; set; }
        public List<WHRestriction> WHRes { get; set; }
        public int SequenceOrder { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public string CountryName { get; set; }
        public string StateName { get; set; }
        public string CityName { get; set; }
        public string PostalCode { get; set; }
        public string CustomerCode { get; set; }
        public bool IsActive { get; set; }
        public int CanAllocate { get; set; }
        public int? WareHouseId { get; set; }
        public string WareHouseName { get; set; }
        public bool? IsManual { get; set; }
        public int SetUpId { get; set; }
        public string SetUpName { get; set; }
        public int UserId { get; set; }
        public List<int> UserIds { get; set; }
        public List<int> ScreenIds { get; set; }
        public Guid ShippingGUID { get; set; }
        public int Skip { get; set; }
        public bool IsServerExport { get; set; }
        public Guid ExcelExportGuid { get; set; }
        public int TotalRecords { get; set; }
        public int ExternalTypeId { get; set; }
        public string SkuType { get; set; }
        public string ChildType { get; set; }
        public string SubChildType { get; set; }
        public string SkuChildType { get; set; }
        public string SkuSubChildType { get; set; }
        public bool IsAllowInvoiceGenerationCp { set; get; }
        public string LabelDetails { get; set; }
    }

} //namespace
